### PR TITLE
2.6.0 TMDb discover & other TMDb special lists

### PR DESCRIPTION
**Pull request by meisnate12**
### Added
- #107 - Added `plex_collection`
- #86 - Added `tmdb_company` and `tmdb_network`
- #41 - Added `tmdb_discover`
- Added `tmdb_popular`, `tmdb_top_rated`, `tmdb_now_playing`

### Fixed
- #108 - Fixed TMDb error
- #102 - If any APIs are invalid the collection switches to append

### CODE REVIEW

**Comment by burkasaurusrex** [comment]
(FYI you can auto-link issues so they close when this is merged: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by burkasaurusrex** [comment]
Just went through this quickly - looks like good work to me.

Feature velocity has been incredible @meisnate12. After this merge, should we take a breath on adding features and write tests? I think some unit testing would help stability going forward. I don't know Python that well, but I should be able to help after next week. I think it'll save our sanity as the complexity continues to grow.

**Comment by mza921** [comment]
I agree on the feature velocity. For everyone claiming not to know Python well, the script is not too shabby! Thanks for all the contributions. I definitely would like to get some unit testing and enhanced logging, followed by performance enhancements.

**Review by mza921 — APPROVED** [review]

**Comment by meisnate12** [comment]
lol this project is the first python code I've ever written, I'm mainly a Java programmer. I was looking at the tmdbv3api and I did a pull there to add trending and had to add my tests that were automatically run it was pretty cool. +1 for actual logging vs just prints. Also, I have been working on creating a dictionary to speed up performance I was going to try and get that working along with the multiple configs for my next release.

**Comment by meisnate12** [comment]
@burkasaurusrex I was wondering how to link issues thanks

**Pull request merged**
